# Instruction + template repo: https://github.com/FedericoPonzi/rust-ci
name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: List files in directory
        run: pwd && ls -lah . && ls -lah ../

      - name: cargo fmt -- --check
        run: cargo fmt --all -- --check
=======
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          profile: minimal
          override: true

      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
>>>>>>> parent of 5b02dd6 (Update automatic_release.yaml)

  deploy:
    name: deploy
    needs: [style]
    #if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [ mips-unknown-linux-musl ]
    steps:
<<<<<<< HEAD
=======
      - name: Checkout
        uses: actions/checkout@v1
>>>>>>> parent of 5b02dd6 (Update automatic_release.yaml)
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build target
<<<<<<< HEAD
        run: cargo build --release --target ${{ matrix.target }}
=======
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
>>>>>>> parent of 5b02dd6 (Update automatic_release.yaml)

      - name: Package
        shell: bash
        run: |
          strip target/${{ matrix.target }}/release/iot_gateway
          cd target/${{ matrix.target }}/release          
          tar czvf ../../../iot_gateway-${{ matrix.target }}.tar.gz iot_gateway
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        # TODO: if any of the build step fails, the release should be deleted.
        with:
            files: 'iot_gateway*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}